// Code generated by fizzbee-mbt generator; DO NOT EDIT.

use fizzbee_mbt::error::MbtError;
use fizzbee_mbt::traits::*;
use fizzbee_mbt::types::Arg;
use fizzbee_mbt::value::Value;
use std::sync::Arc;
use async_trait::async_trait;

// Role traits

#[async_trait]
pub trait WriterRole: AsyncRole {
    async fn action_put(&self, args: &[Arg]) -> Result<Value, MbtError>;
    async fn action_get(&self, args: &[Arg]) -> Result<Value, MbtError>;
    async fn action_flush(&self, args: &[Arg]) -> Result<Value, MbtError>;
}

#[async_trait]
pub trait StorageRole: AsyncRole {
}


// Model trait
pub trait EmbeddedKvstoreModel: Model {
    // R0 is the trait for the WriterRole
    type R0: WriterRole;
    fn get_writer_roles(&self) -> Result<Vec<Arc<Self::R0>>, MbtError>;
    // R1 is the trait for the StorageRole
    type R1: StorageRole;
    fn get_storage_roles(&self) -> Result<Vec<Arc<Self::R1>>, MbtError>;

    // Top-level actions
}