// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../../../../../fizzbee-mbt-quickstart/specs/simple-counter/counter.fizz

package org.example.counter;

import io.fizzbee.mbt.types.Arg;
import io.fizzbee.mbt.types.NotImplementedException;
import io.fizzbee.mbt.types.Role;

public interface CounterRole extends Role {

    

    
    Object actionInc(Arg[] args) throws NotImplementedException;
    

    
    Object actionGet(Arg[] args) throws NotImplementedException;
    

    
    Object actionDec(Arg[] args) throws NotImplementedException;
    

}