// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../../../../../fizzbee-mbt-quickstart/specs/simple-counter/counter.fizz

package org.example.counter;

import io.fizzbee.mbt.types.Arg;
import io.fizzbee.mbt.types.Model;
import io.fizzbee.mbt.types.NotImplementedException;

// Model interface for the whole specification
public interface CounterModel extends Model {

    

}