// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../../../../spec/todo.fizz

package org.example.todo;

import io.fizzbee.mbt.types.Arg;
import io.fizzbee.mbt.types.Model;
import io.fizzbee.mbt.types.NotImplementedException;

// Model interface for the whole specification
public interface TodoModel extends Model {

    

}