// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../../../../spec/todo.fizz

package org.example.todo;

import io.fizzbee.mbt.runner.FizzBeeTestBase;
import io.fizzbee.mbt.types.Arg;
import org.junit.jupiter.api.BeforeAll;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;

public abstract class TodoTestBase extends FizzBeeTestBase {

    @BeforeAll
    public static void setup() {
        try {
            // Top-level model actions (role key = "")
            Map<String, Method> modelActions = new HashMap<>();
            
                
            
            actions.put("", modelActions);

            // Role-specific actions
            
            Map<String, Method> actionsTodoApp = new HashMap<>();
                
                    
                
                    
            actionsTodoApp.put("CreateTodo", TodoAppRole.class.getMethod("actionCreateTodo", Arg[].class));
                    
                
                    
            actionsTodoApp.put("UpdateTodo", TodoAppRole.class.getMethod("actionUpdateTodo", Arg[].class));
                    
                
                    
            actionsTodoApp.put("DeleteTodo", TodoAppRole.class.getMethod("actionDeleteTodo", Arg[].class));
                    
                
                    
            actionsTodoApp.put("ReadTodo", TodoAppRole.class.getMethod("actionReadTodo", Arg[].class));
                    
                
                    
            actionsTodoApp.put("ListTodo", TodoAppRole.class.getMethod("actionListTodo", Arg[].class));
                    
                
                    
            actionsTodoApp.put("PinTodo", TodoAppRole.class.getMethod("actionPinTodo", Arg[].class));
                    
                
                    
            actionsTodoApp.put("UnPinTodo", TodoAppRole.class.getMethod("actionUnPinTodo", Arg[].class));
                    
                
            actions.put("TodoApp", actionsTodoApp);
            

        } catch (NoSuchMethodException e) {
            throw new RuntimeException("Failed to register actions", e);
        }
    }

}