/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.counter.PgCounter;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.UUID;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException {
        System.out.println(new App().getGreeting());
        PgCounter pgCounter = createPgCounter();
        System.out.println("Initial counter value: " + pgCounter.get());
        pgCounter.inc();
        System.out.println("Counter value after increment: " + pgCounter.get());
        pgCounter.inc();
        System.out.println("Counter value after increment: " + pgCounter.get());
        pgCounter.inc();
        System.out.println("Counter value after increment: " + pgCounter.get());
        pgCounter.inc();
        System.out.println("Counter value after increment: " + pgCounter.get());

        pgCounter.dec();
        System.out.println("Counter value after decrement: " + pgCounter.get());
        pgCounter.dec();
        System.out.println("Counter value after decrement: " + pgCounter.get());
        pgCounter.dec();
        System.out.println("Counter value after decrement: " + pgCounter.get());
        pgCounter.dec();
        System.out.println("Counter value after decrement: " + pgCounter.get());

    }

    private static PgCounter createPgCounter() throws SQLException {
        // Open connection to PostgreSQL
        Connection db = DriverManager.getConnection(
                "jdbc:postgresql://localhost:5432/postgres",
                "postgres",
                "mysecretpassword"
        );

        // Create a new PGCounter
        String name = "counter-" + UUID.randomUUID();
        return new PgCounter(db, name, 3);
    }
}
