// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../../fizz/buffered_writer.fizz

package writer

import (
	mbt "github.com/fizzbee-io/fizzbee/mbt/lib/go"
)

// Role interfaces

type WriterRole interface {
	mbt.Role
	ActionAppend(args []mbt.Arg) (any, error)
	ActionFlush(args []mbt.Arg) (any, error)
}

// Model interface for the whole specification
type BufferedWriterModel interface {
	mbt.Model
}
