// Code generated by fizzbee-mbt generator; DO NOT EDIT.

package writer

import (
	"log"
	"os"
	"testing"

	mbt "github.com/fizzbee-io/fizzbee/mbt/lib/go"
)

// Registry keyed by role type ("" means top-level model actions)
var actionRegistry = map[string]map[string]mbt.ActionFunc{
	"": {},
	"Writer": {
		"Append": func(inst any, args []mbt.Arg) (any, error) {
			return inst.(WriterRole).ActionAppend(args)
		},
		"Flush": func(inst any, args []mbt.Arg) (any, error) {
			return inst.(WriterRole).ActionFlush(args)
		},
	},
}

func TestBufferedWriter(t *testing.T) {
	model := NewBufferedWriterModel()
	options := GetTestOptions()
	err := mbt.RunTests(t, model, actionRegistry, options)
	if err != nil {
		log.Fatal(err)
	}
}

func TestMain(m *testing.M) {
	mbt.ParseFlags()
	exitCode := m.Run()
	os.Exit(exitCode)
}
