// Code generated by fizzbee-mbt generator; DO NOT EDIT.

use fizzbee_mbt::error::MbtError;
use fizzbee_mbt::traits::*;
use fizzbee_mbt::types::Arg;
use fizzbee_mbt::value::Value;
use std::sync::Arc;
use async_trait::async_trait;

// Role traits

#[async_trait]
pub trait CounterRole: AsyncRole {
    async fn action_inc(&self, args: &[Arg]) -> Result<Value, MbtError>;
    async fn action_get(&self, args: &[Arg]) -> Result<Value, MbtError>;
    async fn action_dec(&self, args: &[Arg]) -> Result<Value, MbtError>;
}


// Model trait
pub trait CounterModel: Model {
    // R0 is the trait for the CounterRole
    type R0: CounterRole;
    fn get_counter_roles(&self) -> Result<Vec<Arc<Self::R0>>, MbtError>;

    // Top-level actions
}