// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../../fizz/embedded_kvstore.fizz

package kvstore_test

import (
    mbt "github.com/fizzbee-io/fizzbee/mbt/lib/go"
)

// Role interfaces

type WriterRole interface {
    mbt.Role
    ActionPut(args []mbt.Arg) (any, error)
    ActionGet(args []mbt.Arg) (any, error)
    ActionFlush(args []mbt.Arg) (any, error)
}

type StorageRole interface {
    mbt.Role
}


// Model interface for the whole specification
type EmbeddedKvstoreModel interface {
    mbt.Model
}