// Code generated by fizzbee-mbt generator; DO NOT EDIT.

import { runTests, ActionFunc } from '@fizzbee/mbt';
import { TodoModelRole, TodoViewRole, TodomvcModel } from './todomvc_interfaces.js';
import { newTodomvcModel, getTestOptions } from './todomvc_adapters.js';

// Registry keyed by role type ("" means top-level model actions)
const actionRegistry = new Map<string, Map<string, ActionFunc>>([
  ['', new Map<string, ActionFunc>([
  ])],
  ['TodoModel', new Map<string, ActionFunc>([
  ])],
  ['TodoView', new Map<string, ActionFunc>([
    ['UserSwitchesFilter', async (inst: any, args: any[]) => {
      return (inst as TodoViewRole).actionUserSwitchesFilter(args);
    }],
    ['UserAddsItem', async (inst: any, args: any[]) => {
      return (inst as TodoViewRole).actionUserAddsItem(args);
    }],
    ['UserTogglesItem', async (inst: any, args: any[]) => {
      return (inst as TodoViewRole).actionUserTogglesItem(args);
    }],
    ['UserTogglesAll', async (inst: any, args: any[]) => {
      return (inst as TodoViewRole).actionUserTogglesAll(args);
    }],
    ['UserDeletesItem', async (inst: any, args: any[]) => {
      return (inst as TodoViewRole).actionUserDeletesItem(args);
    }],
    ['UserEditsItem', async (inst: any, args: any[]) => {
      return (inst as TodoViewRole).actionUserEditsItem(args);
    }],
    ['UserClearsCompleted', async (inst: any, args: any[]) => {
      return (inst as TodoViewRole).actionUserClearsCompleted(args);
    }],
  ])],
]);

async function testTodomvc(): Promise<void> {
  const model = newTodomvcModel();
  const options = getTestOptions();

  try {
    await runTests(model, actionRegistry, options);
    model.cleanupAll();
  } catch (error) {
    console.error('Test failed:', error);
    process.exit(1);
  }
}

// Run tests
testTodomvc();