// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../spec/todomvc.fizz

import { Role, Model, Arg } from '@fizzbee/mbt';

// Role interfaces

export interface TodoModelRole extends Role {
}

export interface TodoViewRole extends Role {
}

export interface TodoControllerRole extends Role {
  actionUserAddsItem(args: Arg[]): Promise<any>;
  actionUserSwitchesFilter(args: Arg[]): Promise<any>;
  actionUserTogglesItem(args: Arg[]): Promise<any>;
  actionUserTogglesAll(args: Arg[]): Promise<any>;
  actionUserDeletesItem(args: Arg[]): Promise<any>;
  actionUserEditsItem(args: Arg[]): Promise<any>;
  actionUserClearsCompleted(args: Arg[]): Promise<any>;
}

// Model interface for the whole specification
export interface TodomvcModel extends Model {
  // Inherits from Model: init(), cleanup(), getRoles()
}