// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../../../../../fizzbee-mbt-quickstart/specs/simple-counter/counter.fizz

package org.example.counter;

import io.fizzbee.mbt.runner.FizzBeeTestBase;
import io.fizzbee.mbt.types.Arg;
import org.junit.jupiter.api.BeforeAll;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;

public abstract class CounterTestBase extends FizzBeeTestBase {

    @BeforeAll
    public static void setup() {
        try {
            // Top-level model actions (role key = "")
            Map<String, Method> modelActions = new HashMap<>();
            
                
            
            actions.put("", modelActions);

            // Role-specific actions
            
            Map<String, Method> counterActions = new HashMap<>();
                
                    
                
                    
            counterActions.put("Inc", CounterRole.class.getMethod("actionInc", Arg[].class));
                    
                
                    
            counterActions.put("Get", CounterRole.class.getMethod("actionGet", Arg[].class));
                    
                
                    
            counterActions.put("Dec", CounterRole.class.getMethod("actionDec", Arg[].class));
                    
                
            actions.put("Counter", counterActions);
            

        } catch (NoSuchMethodException e) {
            throw new RuntimeException("Failed to register actions", e);
        }
    }

}