// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../../../../spec/todo.fizz

package org.example.todo;

import io.fizzbee.mbt.types.Arg;
import io.fizzbee.mbt.types.NotImplementedException;
import io.fizzbee.mbt.types.Role;

public interface TodoAppRole extends Role {

    

    
    Object actionCreateTodo(Arg[] args) throws NotImplementedException;
    

    
    Object actionUpdateTodo(Arg[] args) throws NotImplementedException;
    

    
    Object actionDeleteTodo(Arg[] args) throws NotImplementedException;
    

    
    Object actionReadTodo(Arg[] args) throws NotImplementedException;
    

    
    Object actionListTodo(Arg[] args) throws NotImplementedException;
    

    
    Object actionPinTodo(Arg[] args) throws NotImplementedException;
    

    
    Object actionUnPinTodo(Arg[] args) throws NotImplementedException;
    

}