// Code generated by fizzbee-mbt generator; DO NOT EDIT.

import { runTests, ActionFunc } from '@fizzbee/mbt';
import { TodoAppRole, TodoModel } from './todo_interfaces.js';
import { newTodoModel, getTestOptions } from './todo_adapters.js';

// Registry keyed by role type ("" means top-level model actions)
const actionRegistry = new Map<string, Map<string, ActionFunc>>([
  ['', new Map<string, ActionFunc>([
  ])],
  ['TodoApp', new Map<string, ActionFunc>([
    ['CreateTodo', async (inst: any, args: any[]) => {
      return (inst as TodoAppRole).actionCreateTodo(args);
    }],
    ['UpdateTodo', async (inst: any, args: any[]) => {
      return (inst as TodoAppRole).actionUpdateTodo(args);
    }],
    ['DeleteTodo', async (inst: any, args: any[]) => {
      return (inst as TodoAppRole).actionDeleteTodo(args);
    }],
    ['ReadTodo', async (inst: any, args: any[]) => {
      return (inst as TodoAppRole).actionReadTodo(args);
    }],
    ['ListTodo', async (inst: any, args: any[]) => {
      return (inst as TodoAppRole).actionListTodo(args);
    }],
    ['PinTodo', async (inst: any, args: any[]) => {
      return (inst as TodoAppRole).actionPinTodo(args);
    }],
    ['UnPinTodo', async (inst: any, args: any[]) => {
      return (inst as TodoAppRole).actionUnPinTodo(args);
    }],
  ])],
]);

async function testTodo(): Promise<void> {
  const model = newTodoModel();
  const options = getTestOptions();

  try {
    await runTests(model, actionRegistry, options);
    console.log('All tests passed.');
    model.cleanupAll();
  } catch (error) {
    console.error('Test failed:', error);
    process.exit(1);
  }
}

// Run tests
testTodo();