// Code generated by fizzbee-mbt generator; DO NOT EDIT.
// Source: ../../spec/todo.fizz

import { Role, Model, Arg } from '@fizzbee/mbt';

// Role interfaces

export interface TodoAppRole extends Role {
  actionCreateTodo(args: Arg[]): Promise<any>;
  actionUpdateTodo(args: Arg[]): Promise<any>;
  actionDeleteTodo(args: Arg[]): Promise<any>;
  actionReadTodo(args: Arg[]): Promise<any>;
  actionListTodo(args: Arg[]): Promise<any>;
  actionPinTodo(args: Arg[]): Promise<any>;
  actionUnPinTodo(args: Arg[]): Promise<any>;
}

// Model interface for the whole specification
export interface TodoModel extends Model {
  // Inherits from Model: init(), cleanup(), getRoles()
}